### PR TITLE
[cmdline] Preserve metadata when sending input from CLI client to server

### LINKED ISSUE #271: Can't define dynamic var in nrepl
## Expected behavior

```
% clj
Clojure 1.10.3
user=> (def ^:dynamic *dyn* 1)
#'user/*dyn*
user=> (binding [*dyn* 2] (prn *dyn*))
2
```

## Actual behavior

```
% clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.9.0"}}}' -M -m nrepl.cmdline --interactive
nREPL server started on port 41271 on host localhost - nrepl://localhost:41271
nREPL 0.9.0
Clojure 1.10.3
OpenJDK 64-Bit Server VM 17-ea+19-Debian-1
Interrupt: Control+C
Exit:      Control+D or (exit) or (quit)
user=> (def ^:dynamic *dyn* 1)
Warning: *dyn* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *dyn* or change the name. (NO_SOURCE_PATH:1)
#'user/*dyn*
user=> (binding [*dyn* 2] (prn *dyn*))
Execution error (IllegalStateException) at user/eval2146 (REPL:1).
Can't dynamically bind non-dynamic var: user/*dyn*
```

## Steps to reproduce the problem

See above.

### Clojure version

1.10.3

### Java version

17

### Operating system

Debian Linux

### PR DESCRIPTION
**Pull request by alexander-yakushev**
Fixes #271.

I decided to go with `*print-meta*` route as trying to read an s-expression from the inputstream while preserving it as a string is too cumbersome. This fix should do for now.

When refactoring the cmdline_test file, I also discovered #351. I couldn't fix it head-on, I created a bug report for now.

---

- [x] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

### CODE REVIEW

File: src/clojure/nrepl/cmdline.clj [hunk 1]
```diff
@@ -111,12 +111,14 @@ Exit:      Control+D or (exit) or (quit)"
           (let [input (read *in* false 'exit)]
             (if (done? input)
               (clean-up-and-exit 0)
-              (do (doseq [res (nrepl/message session {:op "eval" :code (pr-str input)})]
-                    (when (:value res) (value (:value res)))
-                    (when (:out res) (out (:out res)))
-                    (when (:err res) (err (:err res)))
-                    (when (:ns res) (set! *ns* (create-ns (symbol (:ns res))))))
-                  (recur)))))))))
+              (let [code-str (binding [*print-meta* true]
```
Comment (bbatsov) [inline src/clojure/nrepl/cmdline.clj:114]: I think you might want to add some comment here for posterity's sake.

Comment (alexander-yakushev) [reply src/clojure/nrepl/cmdline.clj:116]: Done

**Comment by alexander-yakushev** [comment]
Resolved the conflict.
