### PR TITLE
[Fix #13] Catch ThreadDeath exception thrown by interrupt

### LINKED ISSUE #13: Interrupt of load-file generates java.lang.ThreadDeath exception
At lein prompt (load-file "src/test/core.clj") where core.clj contains (Thread/sleep 10000) then C-c to interrupt.

```
CompilerException java.lang.ThreadDeath, compiling/home/vitoshka/tmp/cidertest/src/blabla/core.clj:1:17)
clojure.lang.Compiler.load (Compiler.java:7142)
clojure.lang.Compiler.loadFile (Compiler.java:7086)
clojure.lang.RT$3.invoke (RT.java:318)
user/eval3418 (form-init8959987907704530559.clj:1)
clojure.lang.Compiler.eval (Compiler.java:6703)
clojure.lang.Compiler.eval (Compiler.java:6666)
clojure.core/eval (core.clj:2927)
clojure.main/repl/read-eval-print-6625/fn-6628 (main.clj:239)
clojure.main/repl/read-eval-print--6625 (main.clj:239)
clojure.main/repl/fn--6634 (main.clj:257)
clojure.main/repl (main.clj:257)
clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn--594 (interruptible_eval.clj:67)
Caused by:
ThreadDeath
java.lang.Thread.stop (Thread.java:836)
clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn--636 (interruptible_eval.clj:204)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.pr-values/pr-values/fn--573 (pr_values.clj:17)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.load-file/wrap-load-file/fn--751 (load_file.clj:77)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
clojure.tools.nrepl.middleware.session/add-stdin/fn--710 (session.clj:235)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
cider.nrepl.middleware.test/wrap-test/fn--3003 (test.clj:199)
clojure.tools.nrepl.middleware/wrap-conj-descriptor/fn--408 (middleware.clj:17)
cider.nrepl.middleware.stacktrace/wrap-stacktrace/fn--2909 (stacktrace.clj:146)
```

In CIDER, eval the buffer with C-c C-k which uses load-file op and then C-c C-b to interrupt. The relevant CIDER issue is [here](https://github.com/clojure-emacs/cider/issues/869).

(from https://dev.clojure.org/jira/browse/NREPL-69)

### PR DESCRIPTION
**Pull request by mallt**
- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests to cover your change(s)
- [x] All tests are passing
- [ ] The new code is not generating reflection warnings
- [x] You've updated the [changelog](../CHANGELOG.md)(that only applies to user-visible changes)

This PR adds handling of ThreadDeath exceptions that can be thrown by an interrupt.

### CODE REVIEW

File: test/clojure/nrepl/core_test.clj [hunk 1]
```diff
@@ -521,3 +521,12 @@
           false-val (first (repl-values session "*print-namespace-maps*"))]
       (is (= true true-val))
       (is (= false false-val)))))
+
+(def-repl-test interrupt-load-file-with-thread-sleep
```
Comment (bbatsov) [inline test/clojure/nrepl/core_test.clj]: I think "with-thread-sleep" here is not needed.

File: src/clojure/nrepl/middleware/interruptible_eval.clj [hunk 2]
```diff
@@ -121,8 +121,10 @@
                                                      :ns (-> *ns* ns-name str)})))
            ;; TODO: customizable exception prints
            :caught (fn [e]
-                     (let [root-ex (#'clojure.main/root-cause e)]
-                       (when-not (instance? ThreadDeath root-ex)
+                     (let [root-ex (#'clojure.main/root-cause e)
```
Comment (bbatsov) [inline src/clojure/nrepl/middleware/interruptible_eval.clj]: For the sake of future readers of the code it'd be nice if you added here the explanations for why this is needed, as it's not immediately obvious.

**Comment by mallt** [comment]
Thanks for the review!

**Comment by bbatsov** [comment]
Thanks for all your recent help! I appreciate it very much!

**Comment by mallt** [comment]
You're very welcome! I use a lot of the tools you work on on a daily basis, so I'm very glad to help! Thanks!
