### PR TITLE
Use actual bind address in server startup message

### LINKED ISSUE #302: nrepl wrongly prefers ip4 on dual stack systems
Starting nrepl with default params (no `-b`) launches it on `127.0.0.1`. It happily reports that it started/bound to `localhost:99999` . Other software (calva) connect via printed message and fails because `::1:99999` (ipv6) is not listened on.

(this started as https://github.com/BetterThanTomorrow/calva/issues/2310)

---

since nrepl binds to a port, it should print the address instead of the host  

## Expected behavior

banner text to print connectable address

`nREPL server started on port 36009 on host localhost - nrepl://127.0.0.1:36009`

or

`nREPL server started on port 36009 on host localhost - nrepl://::1:36009`

## Actual behavior

banner text to port not listed on

`nREPL server started on port 36009 on host localhost - nrepl://localhost:36009`

## Steps to reproduce the problem

1. have a dualstack system (ip4 + ip6)
2. start nrepl (without `-b`)
3. nrepl starts ([hardbinds](https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/socket.clj#L37) to `127.0.0.1`)
4. nrepl prints `nrepl://localhost:36009`
5. calva/some software  wants to connect - resolves localhost - `::1`
6. and finally `nREPL connection failed: Error: connect ECONNREFUSED ::1:36009`

### Clojure version

1.11.1

### Java version

```
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35)
OpenJDK 64-Bit Server VM (build 21+35, mixed mode, sharing)
```

### Operating system

arch linux

---

quickfix:

```diff
diff --git a/src/clojure/nrepl/socket.clj b/src/clojure/nrepl/socket.clj
--- src/clojure/nrepl/socket.clj
+++ src/clojure/nrepl/socket.clj
@@ -207,9 +207,9 @@
           (URI. (str transport-scheme
                      (when (instance? SSLServerSocket sock)
                        "s"))
                 nil ;; userInfo
-                (-> sock .getInetAddress .getHostName)
+                (-> sock .getInetAddress .getHostAddress)
                 (.getLocalPort sock)
                 nil       ;; path
                 nil       ;; query
                 nil)))))) ;; fragment
```

### PR DESCRIPTION
**Pull request by bbatsov**
On dual-stack systems (IPv4 + IPv6), nREPL binds to `127.0.0.1` but prints `nrepl://localhost:PORT` in the startup banner because `as-nrepl-uri` calls `.getHostName` on the server socket. Clients like Calva resolve `localhost` to `::1` (IPv6), fail to connect, and report "connection refused".

This threads the explicit bind address through the Server record so the URI uses exactly what was specified (defaulting to `127.0.0.1`), rather than reverse-resolving the socket address.

Fixes #302, based on #340.

---

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests to cover your changes.
- [x] You've updated the [changelog](../CHANGELOG.md) (only applies to user-visible changes)

### CODE REVIEW

File: src/clojure/nrepl/cmdline.clj [hunk 1]
```diff
@@ -454,16 +453,15 @@ Exit:      Control+D or (exit) or (quit)"
   connection details from.
   Takes nREPL server map and processed CLI options map.
   Returns connection header string."
-  [server options]
+  [{:keys [host port socket] :as server} options]
   (let [transport (:transport options)
-        ^java.net.ServerSocket ssocket (:server-socket server)
-        ^URI uri (socket/as-nrepl-uri ssocket (transport/uri-scheme transport))]
```
Comment (alexander-yakushev) [inline src/clojure/nrepl/cmdline.clj]: Why remove the type hint from here and move it to the callsite? I think it was fine as is.

**Review by alexander-yakushev — APPROVED** [review]
Looks reasonable, with a single nitpick.
